### ISSUE TITLE
run_train_2D.sh error

### ISSUE THREAD

**Issue by bill4u** [ai4ce/DeepMapping#2]
my version of python is :  **Python 3.6.8**
Traceback (most recent call last):
  File "train_2D.py", line 12, in <module>
    import utils
  File "../utils/__init__.py", line 2, in <module>
    from .geometry_utils import *
  File "../utils/geometry_utils.py", line 3, in <module>
    import open3d
  File "/home/ct/.local/lib/python3.6/site-packages/open3d/__init__.py", line 28, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: Invalid character class.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "train_2D.py", line 12, in <module>
    import utils
  File "../utils/__init__.py", line 2, in <module>
    from .geometry_utils import *
  File "../utils/geometry_utils.py", line 3, in <module>
    import open3d
  File "/home/ct/.local/lib/python3.6/site-packages/open3d/__init__.py", line 28, in <module>
    from .open3d import * # py2 py3 compatible
ImportError: Invalid character class.

So is there anything I can do to solve this error? thx

**Comment by dmax123** [comment]
Hi bill4u, could you provide your open3d and pytorch versions?

**Comment by bill4u** [comment]
> Hi bill4u, could you provide your open3d and pytorch vers

HELLO, thx for your reply. Here's versions:

open3d_python-0.7.0.0-cp36-cp36m-manylinux1_x86_64
torch-1.1.0-cp36-cp36m-manylinux1_x86_64

they are installed by typing the command : pip3 install -r requirements.txt

**Comment by dmax123** [comment]
Thanks. Looks like some conflicts between the packages in these versions. I am digging into this but for now please try Open3d v0.4 and Pytorch v0.4.1 (I've updated the requirements.txt). These versions should work.
